### ISSUE TITLE
Uncaught ReferenceError: __filename is not defined in feeder-node.worker.js:1:3864

### ISSUE THREAD

**Issue by DavideC84** [aolsenjazz/feeder-node#95] opened 2024-02-08 16:38 UTC
Hello!
Thanks for your audioworklet node. I have been trying to use it in one of my projects (pure javascript and HTML, without node.js) but as soon as i initialize it, i get this error:

![image](https://github.com/aolsenjazz/feeder-node/assets/53974495/9ac81f7d-16d3-417c-ad12-1df689b8db1e)

The same happens if i try to execute your examples. 

Here's the code i'm using:

    var context   = new AudioContext({sampleRate:8000, sampleSize:16});
    var nChannels = 2;
    let options = {
        inputSampleRate:     context.sampleRate, 
    
        batchSize:           128, 
        bufferThreshold:     4096,         
        bufferLength:        192000,       
        resampConverterType: 2,            
    
        pathToWorklet:       '/audiotest2/dist/feeder-node.worklet.js',
        pathToWorker:        '/audiotest2/dist/feeder-node.worker.js',    
        pathToWasm:          '/audiotest2/dist/libsamplerate.wasm'     
    }
    function createAudioCtx() {

    FeederNode.createFeederNode(context, nChannels, options)
    .then((feederNode) => {
        feederNode.connect(context.destination);
        });			
      }

Am i missing something?

Thanks for your time.
Davide

**Comment by aolsenjazz** [comment] 2024-02-08 17:05
Hey Davide, thanks for submitting this! Weird that a node global managed to get into the dist files, but this must be a compilation/webpack error. Are you able to share your project or provide instructions to reproduce? Looks like the common config in in `webpack.config.js` is targeting node, so I'll bet that's where this slipped in.

Will have some time later today to check it out.

**Comment by DavideC84** [comment] 2024-02-09 08:16
Hi Alexander!
Thanks a lot for getting back to me.

Sure i can share the code but it's nothing special or really complicated, it was just a test i was writing to test your feederNode and then include it in my project (i already wrote my own audioworklet node i feed with realtime audio data coming from a websocket but looks like i'm having problems with buffer and audio thread timing so i was looking for other solutions from someone better than me :-)).  You'll find the code i'm having troubles with.
Just click on "Create ctx" button and the error displays.

I think you can reproduce the error i'm having just without using node.js. My code is hosted on a linux machine with apache2 as webserver. 
Alternatively, i can also reproduce it by executing the page locally on my Windows machine (must disable cors on chrome tho).

Please tell me if there's anything else i can do to help you with and thanks for everything.

[audiotest2.tar.gz](https://github.com/aolsenjazz/feeder-node/files/14219263/audiotest2.tar.gz)

**Comment by aolsenjazz** [comment] 2024-02-10 18:04
Thanks for the additional info. Commit 8589750d4e388a62c162946f665fb036317e25bb fixes this - please upgrade to v1.1.3 and confirm if it's working on your end!

**Comment by aolsenjazz** [comment] 2024-02-10 18:48
Oh - and especially glad to help out another musician!

**Comment by DavideC84** [comment] 2024-02-10 22:02
Hey! Alexander, works LIKE A CHARM!!!
Installed the new version with your bugfixes and fixed couple of things here and there in my code (like, i had to pass to the feeder a TypedArray :)) and i was finally able to record audio from my first audio-worklet, buffer it in chunks and pass the cunks to your feeder node which reproduces the audio without a flow! It's literally AWESOME! It even works great on mobile phone! I'm really without words for your great work. I'll now have to understand how you managed to code such a powerful and well working solution and learn something from your craft! :) 
Can't wait to use your feeder node with the other parts of my project (opus encoding/decoding, websocket to stream the data etc..)! You made my day. Warm regards!  

P.s. when and if i'll put online my project you can be sure i'll be crediting you.

**Comment by aolsenjazz** [comment] 2024-02-10 22:05
So glad it worked out! It’s a powerful feeling when things come together. Closing this. Happy hacking and let me know how the project turns out!

**Closed as completed by aolsenjazz** 2024-02-10 22:05 UTC
